version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:017500899605:task-definition/lkgclass-book-manager:1" 
        LoadBalancerInfo:
          ContainerName: "book-manager"
          ContainerPort: 8080
